#!/bin/sh

# Creates new file
DATE=$(date)

if  [ ! $1 ]; then
  echo Please add a post name
  exit
fi

echo $1
echo "---
  date: $DATE
  keywords:
---
" > posts/$1.md

nvim posts/$1.md

# Generates index file

# Sync to repo
git add .
git commit -m "$DATE Update: $1"
git push
