#!/bin/sh

DATE=$(date)

echo "---
  title: Index
  date: $DATE
  disclaimer: Here are only shown the newest 10 pages. If you want to check older posts, go to the github page.
---

# Recent posts
" > index.md

for POST in $(find ./posts/*.md -printf '%T@ %p\n' | sort -k1 -n -r | cut -d ' ' -f2- | head -n 10) 
do 
  echo "* [$(grep 'title:' $POST | head -n 1 | cut -c 10-)]($POST)" >> index.md
  pandoc $POST -o target/${POST%.md}.html --template=templates/posts.html
  sed -i 's/.md/.html/g' target/${POST%.md}.html
done

pandoc index.md -o target/index.html --template=templates/index.html
sed -i 's/.md/.html/g' target/index.html
